# Generated by Django 4.1.5 on 2023-03-24 03:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0002_alter_hotel_address_alter_hotel_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotelavailability',
            name='hotel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hotels.hotel'),
        ),
    ]
