# Generated by Django 4.1.7 on 2023-03-24 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0003_alter_hotelavailability_hotel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation",
            options={"ordering": ["-start_date"]},
        ),
        migrations.AddField(
            model_name="reservation",
            name="guests",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
