# Generated by Django 4.1.7 on 2023-03-05 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=120)),
                ('inst_num', models.IntegerField(max_length=120)),
                ('swift_code', models.CharField(max_length=120)),
            ],
        ),
    ]
