# Generated by Django 4.1.7 on 2023-03-05 23:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='inst_num',
            field=models.CharField(max_length=120),
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('transit_num', models.CharField(max_length=120)),
                ('address', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branches', to='banks.bank')),
            ],
        ),
    ]
