# Generated by Django 4.1.7 on 2023-03-06 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0002_alter_bank_inst_num_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='capacity',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
