# Generated by Django 4.1.7 on 2023-03-06 00:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0003_alter_branch_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='last_modified',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
