# Generated by Django 4.1.7 on 2023-03-07 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0011_alter_branch_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
