# Generated by Django 4.1.7 on 2023-03-07 19:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('banks', '0013_alter_branch_capacity_alter_branch_last_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='last_modified',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
