# Generated by Django 4.1.7 on 2023-03-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0005_reply_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='reply',
            name='detail',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
