# Generated by Django 4.1.5 on 2023-04-24 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0006_reply_detail'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='state',
            field=models.CharField(choices=[('A', 'Approved'), ('P', 'Pending'), ('Ca', 'Cancelled'), ('D', 'Denied'), ('E', 'Expired'), ('T', 'Terminated'), ('F', 'Finished')], default='P', max_length=100),
        ),
    ]
