# Generated by Django 4.1.5 on 2023-05-02 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0010_remove_notification_sender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 2, 6, 40, 47, 907268)),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='state',
            field=models.CharField(choices=[('A', 'Approved'), ('P', 'Pending'), ('Ca', 'Cancelled'), ('D', 'Denied'), ('E', 'Expired'), ('T', 'Terminated'), ('F', 'Finished'), ('PC', 'PendingCancel')], default='P', max_length=100),
        ),
    ]
