# Generated by Django 4.1.5 on 2023-05-02 08:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotels', '0012_alter_notification_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='notification',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 2, 8, 7, 58, 660679)),
        ),
    ]
