# Generated by Django 4.1.7 on 2023-02-26 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_myuser_password1_remove_myuser_password2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
