# Generated by Django 4.1.7 on 2023-03-05 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_delete_myuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Branch',
        ),
    ]
